#!/bin/bash

echo "🔧 Aplicando fix de RLS para invoices..."
echo ""
echo "INSTRUCCIONES:"
echo "1. Abre en tu navegador:"
echo "   https://supabase.com/dashboard/project/juygffhwqpjpmwgajcwj/sql/new"
echo ""
echo "2. Copia este SQL y pégalo en el editor:"
echo ""
echo "════════════════════════════════════════════════════════════════"
cat supabase/fix-invoices-rls.sql
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "3. Haz click en 'Run' (o presiona Cmd/Ctrl + Enter)"
echo ""
echo "4. Deberías ver: 'Success. No rows returned'"
echo ""
echo "5. Recarga la app y ya NO tendrás el error 403"
echo ""
echo "¿Por qué no lo hago automáticamente?"
echo "Supabase no permite ejecutar SQL arbitrario desde scripts por seguridad."
echo "Debes hacerlo desde el dashboard web."
